AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Deploy a lambda function that maintains the records status model state

Parameters:
  CodeBucketName:
    Type: String
    Description: Bucket containing lambda code zip file
  ZipFileName:
    Type: String
    Default: smssub-deployment.zip


Resources:

  SMSSubTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: InstanceID
          AttributeType: S
        - AttributeName: Notify
          AttributeType: S
      KeySchema:
        - AttributeName: InstanceID
          KeyType: HASH
        - AttributeName: Notify
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        'Fn::Join':
          - '-'
          - - !Ref 'AWS::StackName'
            - Subscribers

#  SMSSubFunction:
#    Type: "AWS::Lambda::Function"
#    Properties:
#      Handler: "main"
#      Role: !GetAtt SMSSubExecutionRole.Arn
#      Code:
#          S3Bucket: !Ref CodeBucketName
#          S3Key: !Ref ZipFileName
#      Runtime: "go1.x"
#      Timeout: 60
#      Environment:
#        Variables:
#          SUBSCRIPTION_TABLE: !Ref SMSSubTable

  SMSSubFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Role: !GetAtt SMSSubExecutionRole.Arn
      CodeUri:
        Bucket: !Ref CodeBucketName
        Key: !Ref ZipFileName
      Runtime: go1.x
      Tracing: Active
      Environment:
        Variables:
          SUBSCRIPTION_TABLE: !Ref SMSSubTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post




  SMSSubExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: logs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
      - PolicyName: metrics
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            Resource: '*'
      - PolicyName: xray
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - xray:PutTelemetryMetrics
            - xray:PutTraceSegments
            Resource: '*'
      - PolicyName: ddb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:PutItem
            Resource: !GetAtt SMSSubTable.Arn
